language: node_js
node_js: 
  - '5'
sudo: required
services:
  - docker

after_success:
  # - ls -a 
  # - pwd
  # - which node
  - docker build -t bablot/travis-test .
  - docker push bablot/travis-test