sudo: required
language: node_js
node_js:
- '5'
after_success:
  - echo $DEPLOY_HOST
env:
  global:
    secure: ioauKX35peOcbmv5/HVC+5trtonY/IvgeZa9yhWe7Erd74uOA6HRKrsswX2QNiTZVf98GVjFPBMGHHH5dbjuhP+cLWhxP/ZCW8heQlPnpJ0BHcQqNZoSJfzAfoMrvwOVei29nPfOniy7xw8ZhfFYzF5j5YwykoBg4h30RlvvjG1EHlqfgnUgVF6Zrq0LRAIy7UbzZ6Olxb9tcRUy/ll1RZ6BkYy7Zgn3kp9vBnO/3jOj4Zuf9IKHZNKMvNV0zMYeLyCXOhqk5CBwIDH2BuW6nPZ7hM2Ve1bWFiNe6ENeMbaLg8jeCitarC3dFf0IIDDiDDDAZUBPFkf4ePlCp7hDbP4ZDRIvELVepG+pQkONC6PNqteUBsDe/vkzTLXTKZltQ1UmbzrehrqmaVcKumFR6BJmm06rvkAdcBkd3y5XL6ilLlClTwqkxK/q/VlFMVegVgrCo2IaKULWJwobee3CTFNWIwgFHmC2u4kkExjX6dPZyKNkdzFhtu8znqNlC96gGjqETuS+c+MJ2OdRyRpTTIcvm6owMmR1TqlEyIWImw6lXO/OTk7lHZwGgIESNiQp0y9XkKcSrCueR7BrBmsWv08/h2kMd10H5A+vSRyiP47dFla8Pj2OOLT4ZjPwXcYkOLHXUKTOxF8pBsaHmNOEdJWWBvW4gzfRpDceHpJn1T4=
